Repository eifinger/setup-rye, pull requests merged in 2024-07, with the labels that each got.

#282 Distinguish cache and tools-cache in log message
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  src/restore-cache.ts
  src/save-cache.ts
  src/setup-rye.ts
Labels: enhancement

#285 Remove duplicate message on local cache miss
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  src/restore-cache.ts
Labels: bugfix

#287 Check for wrong venv path in cache
  .github/workflows/test-cache.yml
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  src/restore-cache.ts
Labels: bugfix

#288 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#294 Explicitly exit after this action runs to not wait for hanging promises
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  src/save-cache.ts
  src/setup-rye.ts
Labels: bugfix

#299 Add automatic toolchain version detection
  .github/workflows/test-latest.yml
  dist/save-cache/index.js
  dist/save-cache/index.js.map
  dist/setup/index.js
  dist/setup/index.js.map
  src/restore-cache.ts
  src/save-cache.ts
  src/setup-rye.ts
Labels: enhancement

#300 docs: update v3 to v4 in README
  README.md
Labels: documentation

#305 Add FAQ section
  README.md
Labels: documentation
